### PR TITLE
Dashboard HTML file created

### PR DESCRIPTION
**Pull request by A1zenSousuke**
Issue #8 
@Codehackerone I have created the Dashboard file. If you want some changes I can do it .

### CODE REVIEW

**Comment by Codehackerone** [comment]
Can you share a ss?
and put it under ``templates`` folder

**Comment by A1zenSousuke** [comment]
@Codehackerone here is the [ss](https://www.awesomescreenshot.com/image/30760531?key=0a411fe3d95e97ad2c45cc5b0107bb39)

**Comment by A1zenSousuke** [comment]
if you want it to made in some different structure do let me know I will make it.

**Comment by Codehackerone** [comment]
Your page looks good but too basic. Can you add some more styling to it

**Comment by A1zenSousuke** [comment]
@Codehackerone  thats why I wanted to know what stuff do you need me to add .like an example or something

**Comment by Codehackerone** [comment]
image

Some what like the bottom portion of the image

**Comment by A1zenSousuke** [comment]
OK I will give it a try

**Comment by A1zenSousuke** [comment]
OCR Text Recognition (1)
Is this ok @Codehackerone ?

**Comment by Codehackerone** [comment]
Looks good. Just use ``assets`` to store the CSS and js files

**Comment by A1zenSousuke** [comment]
@Codehackerone I have added the assets folder.

**Review by Codehackerone — APPROVED** [review]
Great work!!

**Pull request merged**
